services:
  web:
    build:
      context: .
      args:
        requirements_file: requirements.txt
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - .:/tbi
      - ./data:/data
    depends_on:
      - mongodb
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env
    restart: always
    networks:
      - app-network
  
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:

